### PR TITLE
Clientside

### PR DESCRIPTION
**Pull request by apsitos**
Client side breaks apart the address and reconnects with '+' for proper insertion into geocode API call.

HOWEVER, state of 'formatted' is not being set, despite its appearance in the React dev tools. When 'this.state.formatted' is logged, console shows a blank.

@applegrain, Can you help me with this issue?

### CODE REVIEW

**Comment by biglovisa** [comment]
@apsitos so I think it's because the state is not actually set until you have left that function you are setting it in. When you call `this.showBars`, the state hasn't been updated yet since you haven't left the function where you are setting it. 
You can pass callbacks to `setState` that will be executed once the state has been set. You can try to do something like : `this.setState({ formatted: streetAddress }, () => this.showBars() )`.

**Comment by apsitos** [comment]
That worked!! I had no idea you could do that. Thank you!!

**Comment by apsitos** [comment]
Woo! The address now correctly adjusts so there are '+' signs between each word, and the address sends to the back end. I may have to move the split and join function because it didn't appear in the terminal console.log correctly.

**Comment by biglovisa** [comment]
Yeah it's a small quirk of react that's useful to know! Fortunately there's an easy work around :)

**Pull request merged**
